### ISSUE TITLE
Crash when pressing a button with leaves nearby

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [CplPibald/PiTweaks#20]
PiTweaks version:1.16.5-1.3.3
Forge:36.2.9
Reproduce screenshot:
![2021-11-20_16 51 05](https://user-images.githubusercontent.com/37864486/142720977-88db7221-0d4e-4c53-9fdb-3a20c74080db.png)
Either of these two buttons will crash if pressed.

Crash report:https://pastebin.com/t7e7uRix

**Comment by Borbarad13** [comment]
Same behavior when there is a comparator next to a leave and you toggle the comparator.


```
java.lang.ClassCastException: net.minecraft.client.world.ClientWorld cannot be cast to net.minecraft.world.server.ServerWorld
	at us.bemrose.mc.pitweaks.ForestTweak.onNotify(ForestTweak.java:37) ~[pitweaks:1.16.5-1.3.3] {re:classloading}
```

**Comment by Borbarad13** [comment]
Extended log:
```
[17Dec2021 03:02:21.033] [Render thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: net.minecraft.client.world.ClientWorld cannot be cast to net.minecraft.world.server.ServerWorld
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: us.bemrose.mc.pitweaks.ForestTweak@f1683cc onNotify(Lnet/minecraftforge/event/world/BlockEvent$NeighborNotifyEvent;)V
java.lang.ClassCastException: net.minecraft.client.world.ClientWorld cannot be cast to net.minecraft.world.server.ServerWorld
	at us.bemrose.mc.pitweaks.ForestTweak.onNotify(ForestTweak.java:37)
	at net.minecraftforge.eventbus.ASMEventHandler_2766_ForestTweak_onNotify_NeighborNotifyEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.event.ForgeEventFactory.onNeighborNotify(ForgeEventFactory.java:174)
	at net.minecraft.world.World.func_175695_a(World.java:305)
	at net.minecraft.block.RedstoneDiodeBlock.func_176400_h(RedstoneDiodeBlock.java:169)
	at net.minecraft.block.ComparatorBlock.func_176462_k(ComparatorBlock.java:135)
	at net.minecraft.block.ComparatorBlock.func_225533_a_(ComparatorBlock.java:98)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227031_a_(AbstractBlock.java:640)
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:288)
	at net.optifine.override.PlayerControllerOF.func_217292_a(PlayerControllerOF.java:97)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1368)
	at net.minecraft.client.Minecraft.redirect$zmn000$onDoItemUse(Minecraft.java:4534)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1647)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1462)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:954)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:35)
	at net.minecraft.client.Minecraft.modify$zlc000$atTheEndOfSecondCatchBeforePrintingCrashReport(Minecraft.java:4055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:631)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


[17Dec2021 03:02:21.052] [Render thread/FATAL] [net.minecraft.client.Minecraft/]: Unreported exception thrown!
java.lang.ClassCastException: net.minecraft.client.world.ClientWorld cannot be cast to net.minecraft.world.server.ServerWorld
	at us.bemrose.mc.pitweaks.ForestTweak.onNotify(ForestTweak.java:37) ~[pitweaks:1.16.5-1.3.3]
	at net.minecraftforge.eventbus.ASMEventHandler_2766_ForestTweak_onNotify_NeighborNotifyEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.event.ForgeEventFactory.onNeighborNotify(ForgeEventFactory.java:174) ~[forge:?]
	at net.minecraft.world.World.func_175695_a(World.java:305) ~[?:?]
	at net.minecraft.block.RedstoneDiodeBlock.func_176400_h(RedstoneDiodeBlock.java:169) ~[?:?]
	at net.minecraft.block.ComparatorBlock.func_176462_k(ComparatorBlock.java:135) ~[?:?]
	at net.minecraft.block.ComparatorBlock.func_225533_a_(ComparatorBlock.java:98) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227031_a_(AbstractBlock.java:640) ~[?:?]
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:288) ~[?:?]
	at net.optifine.override.PlayerControllerOF.func_217292_a(PlayerControllerOF.java:97) ~[?:?]
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1368) ~[?:?]
	at net.minecraft.client.Minecraft.redirect$zmn000$onDoItemUse(Minecraft.java:4534) ~[?:?]
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1647) ~[?:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1462) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:954) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:35) ~[notenoughcrashes:?]
	at net.minecraft.client.Minecraft.modify$zlc000$atTheEndOfSecondCatchBeforePrintingCrashReport(Minecraft.java:4055) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:631) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.20-launcher.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:53) [ForgeWrapper-mmc1.jar:mmc1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```
